# Generated by Django 4.2.4 on 2023-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_order_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.UUIDField(),
        ),
    ]
